ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/shop/urls.py
from django.urls import path

from . import views
app_name='shop'

urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodetail,name='procatdetail'),
]

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey (Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:procatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'



    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    products=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products=Product.objects.all().filter(category=c_page,available=True)
    else:
        products=Product.objects.all().filter(available=True)
    return render(request,'category.html',{'category':c_page,'products':products})
def prodetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1,">
    <link rel="atylesheet" href="{% static 'css/custom.css' %}">
      <link href="{% static 'css/bootstrap.min.css' %}"  rel="stylesheet">

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 {% if category %}
     {{category.description|truncatewords:155 }}
 {% else %}
    welcome to online shopping store where you can buys different items...
 {% endif %}
{% endblock %}
{% block title %}

     {% if category %}
          {{category.name }}-online shopping store
     {% else %}
          see our new products
     {% endif %}
 {% endblock %}

{% block content %}
{% if category %}
<div>
     <div class="row my-row-class">
            <div class="mx-auto">
              <p><a href="{% url 'shop:allProdCat' %}">Our product collections </a>{{cat.get_url}}</p>
            </div>
     </div>
</div>
{% endif %}
<div>
    {% if category %}
    <img src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1>{{category.name}}</h1>
    <p>{{category.description}}</p>

</div>
{% else %}
<div>
    <img src="{% static 'img/banner.png' %}" alt="Our Products" width="1250px" height="400px">
</div>
<br>
<div>
<h1>Our product collections</h1>

<p>"Welcome to the Themes team!
We are a group of volunteers who review and approve themes submitted to be included in the official WordPress Theme directory"</p>

</div>
{% endif %}
<div>
    <div>
        {% for product in products %}
        <div>
            <div>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div>
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
{% endfor %}
    </div>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my-footer">
  <p class="text-center">&copy;ABC tech pvt ltd. all rights reseved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"></a><img src="{% static 'img/logo.png' %}" alt="logimage" width="200px" height="200px">
    </center>
</header>

ecommerceproject/templates/nav.html
<!--{% load static %}-->
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->

<!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->

<!--  <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--    <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->

<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">ONLINE SHOP</a>-->
<!--      </li>-->
<!--      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          shop-->
<!--        </a>-->
<!--        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->

<!--           <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>-->
<!--            {% for cat in links %}-->
<!--           <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--      </li>-->

<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">your Cart()</a>-->
<!--      </li>-->
<!--    </ul>-->
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
<!--  </div>-->
<!--</nav>-->


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>

    </button>
  </li>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <p><a class="nav-link" href="{% url 'shop:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>

<!--           href="#">Home <span class="sr-only"></span></a>-->
      </li>

      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          categories
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}"></a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}</a>
<!--          <a class="dropdown-item" href="{{product.category.get_url}}">{{cat.name}}</a>-->
          <a class="dropdown-item" href="{{cat.get_url}}">{{category.name}}</a>
          <div class="dropdown-divider"></div>

        </ul>
      </div>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">your cart</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{ product.description|truncatewords:155 }}


{% endblock %}
{% block title %}
  {% if category %}
    {{product.name }} -online store
  {% endif %}
{% endblock %}

{% block content %}
<div>
    <div>
        <p><a href="{% url 'shop:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<br>
<div>
    <div>
        <div>
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
    <div>
        <div>
            <h1>{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p>Product Description</p>
             <p>{{product.description}}</p>
            {% if product.stock <= 0 %}
                <p><b>Out of stock</b></p>
            {% else %}
            <a href="">add to cart</a>
            {% endif %}
            {% endblock %}
        </div>
    </div>
</div>